name: Metrics
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.people.repository.svg
  token: ${{ secrets.METRICS }}
  base: ""
  template: repository
  repo: metrics
  plugin_people: yes
  plugin_people_types: contributors, stargazers, watchers, sponsors
